LT-4061: CandlesHistory: add api to fetch low/high/eod mid prices for each period
LykkeBusiness/Lykke.Service.CandlesHistory pull request #44
Opened 2022-07-14 11:32 UTC by lykke-vashetsin

2022-08-04 13:10 UTC, anokhin-lkk requested changes
Let's discuss this task

2022-08-04 13:10 UTC, anokhin-lkk commented on src/Lykke.Service.CandleHistory.Repositories/Candles/CandlesHistoryRepository.cs
> +            throw new NotImplementedException();
Why not implemented?

2022-08-19 12:23 UTC, tarurar approved these changes

2022-08-19 12:23 UTC, tarurar commented on src/Lykke.Service.CandleHistory.Repositories/Candles/CandlesHistoryRepository.cs
> +            throw new NotImplementedException();
Is it intentionally?

2022-08-19 12:23 UTC, tarurar commented on src/Lykke.Service.CandleHistory.Repositories/Candles/SqlAssetPairCandlesHistoryRepository.cs
> +        [CanBeNull]
I think `[ItemCanBeNull]` is more appropriate here.

2022-08-19 12:23 UTC, tarurar commented on src/Lykke.Service.CandleHistory.Repositories/Candles/SqlAssetPairCandlesHistoryRepository.cs
> +        [CanBeNull]
Same here.

2022-08-19 12:28 UTC, lykke-vashetsin commented on src/Lykke.Service.CandleHistory.Repositories/Candles/CandlesHistoryRepository.cs
> +            throw new NotImplementedException();
it is for azure which we don't use

2022-08-19 12:31 UTC, lykke-vashetsin commented on src/Lykke.Service.CandleHistory.Repositories/Candles/SqlAssetPairCandlesHistoryRepository.cs
> +        [CanBeNull]
deleted at all, not sure how it comes here :)

2022-08-19 12:33 UTC, tarurar approved these changes

2022-08-19 12:41 UTC, merged